gateway:
  gw:
    enable_http: true
    enable_socket: true
    outer_http_server:
      listen_address: 0.0.0.0:5000
      outer_host: ""
      tls_cert_file: ""
      tls_key_file: ""
      allow_cross: true
    outer_socket_server:
      tls_cert_file: ""
      tls_key_file: ""
      default_session_age: 0s
      default_context_age: 0s
      slow_comet_duration: 0s
      default_body_codec: ""
      print_detail: true
      count_time: true
      network: ""
      listen_address: 0.0.0.0:5020
      enable_heartbeat: true
    inner_socket_server:
      tls_cert_file: ""
      tls_key_file: ""
      default_session_age: 0s
      default_context_age: 0s
      slow_comet_duration: 0s
      default_body_codec: ""
      print_detail: true
      count_time: true
      network: ""
      listen_address: 0.0.0.0:5030
      enable_heartbeat: true
    inner_socket_client:
      tls_cert_file: ""
      tls_key_file: ""
      default_session_age: 0s
      default_context_age: 0s
      default_dial_timeout: 0s
      redial_times: 0
      failover: 3
      slow_comet_duration: 0s
      default_body_codec: ""
      print_detail: false
      count_time: false
      network: ""
      heartbeat_second: 60
      sess_max_quota: 0
      sess_max_idle_duration: 0s
      circuit_breaker:
        enable: false
        error_percentage: 0
        break_duration: 0s
    etcd:
      endpoints:
      - http://127.0.0.1:2379
      dial_timeout: 0s
      username: ""
      password: ""
  redis:
    deploy_type: single
    for_single:
      addr: 127.0.0.1:6379
    for_cluster:
      addrs: []
    pool_size_per_node: 0
    idle_timeout: 0

server:
  etcd:
    dial_timeout: 0s
    endpoints:
    - http://127.0.0.1:2379
    password: ""
    username: ""
  redis:
    deploy_type: single
    for_cluster:
      addrs: []
    for_single:
      addr: 127.0.0.1:6379
    idle_timeout: 0
    pool_size_per_node: 0
  srv:
    count_time: false
    default_body_codec: ""
    default_context_age: 0s
    default_session_age: 0s
    enable_heartbeat: true
    listen_address: ":"
    network: ""
    print_detail: false
    slow_comet_duration: 0s
    tls_cert_file: ""
    tls_key_file: ""
